# Generated by Django 4.1.4 on 2023-01-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter', models.CharField(max_length=100)),
                ('leave', models.CharField(max_length=100)),
            ],
        ),
    ]
